// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xtirnxassnqrgcyxvhum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inh0aXJueGFzc25xcmdjeXh2aHVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk1NTU4NDIsImV4cCI6MjA2NTEzMTg0Mn0.VLGPAZA9ogK-8cb78bru8pVs20i-G8aKWyaGzJ_UFSI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);